using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Plan_o_Tron_6000.Statics
{
    //Ids der Einzelteile
    public enum ItemId
    {
        Kinderfahrrad = 1,
        Damenfahrrad = 2,
        Herrenfahrrad = 3,
        HinterradgruppeK = 4,
        HinterradgruppeD = 5,
        HinterradgruppeH = 6,
        VorderradgruppeK = 7,
        VorderradgruppeD = 8,
        VorderradgruppeH = 9,
        SchutzblechHintenK = 10,
        SchutzblechHintenD = 11,
        SchutzblechHintenH = 12,
        SchutzblechVorneK = 13,
        SchutzblechVorneD = 14,
        SchutzblechVorneH = 15,
        LenkerCpl = 16,
        SattelCpl = 17,
        RahmenK = 18,
        RahmenD = 19,
        RahmenH = 20,
        KetteK = 21,
        KetteD = 22,
        KetteH = 23,
        Mutter38 = 24,
        Scheibe38 = 25,
        PedalCpl = 26,
        Schraube38 = 27,
        Rohr34 = 28,
        VorderradMontH = 29,
        RahmenUndRaederH = 30,
        FahrradOhnePedaleH = 31,
        Farbe = 32,
        FelgeCplH = 33,
        SpeicheH = 34,
        Nabe = 35,
        Freilauf = 36,
        Gabel = 37,
        Welle = 38,
        Blech = 39,
        Lenker = 40,
        Mutter34 = 41,
        Griff = 42,
        Sattel = 43,
        Stange12 = 44,
        Mutter14 = 45,
        Schraube14 = 46,
        Zahnkranz = 47,
        Pedale = 48,
        VorderradMontK = 49,
        RahmenUndRaederK = 50,
        FahrradOhnePedaleK = 51,
        FelgeCplK = 52,
        SpeicheK = 53,
        VorderradMontD = 54,
        RahmenUndRaederD = 55,
        FahrradOhnePedaleD = 56,
        FelgeCplD = 57,
        SpeicheD = 58,
        Schweissdraht = 59
    }

    //Ids der Arbeitsplätze
    public enum StationId : int
    {
       Eins = 1,
       Zwei = 2,
	   Drei = 3,
	   Vier = 4,
	   Fünf = 5,
	   Sechs = 6,
	   Sieben = 7,
	   Acht = 8,
	   Neun = 9,
	   Zehn = 10,
	   Elf = 11,
	   Zwoelf = 12,
	   Dreizehn = 13,
	   Vierzehn = 14,
	   Fuenfzehn = 15
    }

    //Ids der Arbeitsschritte
	//Erste Ziffer gibt den Arbeitsplatz an
	//Zweite Ziffer gibt die Art des Fahrrads an (K = 1, D = 2, H = 3)
	//Dritte Ziffer zählt hoch
    public enum JobId
    {
        VorderradMontageK = 111,
        VorderradMontageD = 121,
        VorderradMontageH = 131,
        RahmenUndRaederK = 211,
        RahmenUndRaederD = 221,
        RahmenUndRaederH = 231,
        PedalUndStangeK = 212,
        PedalUndStangeD = 222,
        PedalUndStangeH = 232,
        FahrradOhnePedaleK = 311,
        FahrradOhnePedaleD = 321,
        FahrradOhnePedaleH = 331,
        FahrradComplK = 411,
        FahrradComplD = 421,
        FahrradComplH = 431,
        BiegemaschineRahmenK = 611,
        BiegemaschineRahmenD = 621,
        BiegemaschineRahmenH = 631,
        RohrbiegemaschineK = 612,
       	RohrbiegemaschineD = 622,
        RohrbiegemaschineH = 632,
        SchweissplatzSchutzblechVorneK = 711,
        SchweissplatzSchutzblechVorneD = 721,
        SchweissplatzSchutzblechVorneH = 731,
        SchweissplatzRahmenK = 712,
        SchweissplatzRahmenD = 722,
        SchweissplatzRahmenH = 732,
        SchweissplatzSchutzblechHintenK = 713,
        SchweissplatzSchutzblechHintenD = 723,
        SchweissplatzSchutzblechHintenH = 733,
        SchweissplatzPedaleK = 714,
        SchweissplatzPedaleD = 724,
        SchweissplatzPedaleH = 734,
        StanzeSchutzblechVorneK = 811,
        StanzeSchutzblechVorneD = 821,
        StanzeSchutzblechVorneH = 831,
        StanzeRahmenK = 812,
        StanzeRahmenD = 822,
        StanzeRahmenH = 832,
        StanzeSchutzblechHintenK = 813,
        StanzeSchutzblechHintenD = 823,
        StanzeSchutzblechHintenH = 833,
        LackierplatzSchutzblechVorneK = 911,
        LackierplatzSchutzblechVorneD = 921,
        LackierplatzSchutzblechVorneH = 931,
        LackierplatzRahmenK = 912,
        LackierplatzRahmenD = 922,
        LackierplatzRahmenH = 932,
        LackierplatzSchutzblechHintenK = 913,
        LackierplatzSchutzblechHintenD = 923,
        LackierplatzSchutzblechHintenH = 933,
        RadmontageVorneK = 1011,
        RadmontageVorneD = 1021,
        RadmontageVorneH = 1031,
        RadmontageHintenK = 1012,
        RadmontageHintenD = 1022,
        RadmontageHintenH = 1032,
        VorderradNabenMontageK = 1111,
        VorderradNabenMontageD = 1121,
        VorderradNabenMontageH = 1131,
        HinterradNabenMontageK = 1112,
        HinterradNabenMontageD = 1122,
        HinterradNabenMontageH = 1132,
        BiegemaschineSchutzblechVorneK = 1211,
        BiegemaschineSchutzblechVorneD = 1221,
        BiegemaschineSchutzblechVorneH = 1231,
        BiegemaschineSchutzblechHintenK = 1212,
        BiegemaschineSchutzblechHintenD = 1222,
        BiegemaschineSchutzblechHintenH = 1232,
        BlechschereSchutzblechVorneK = 1311,
        BlechschereSchutzblechVorneD = 1321,
        BlechschereSchutzblechVorneH = 1331,
        BlechschereSchutzblechHintenK = 1312,
        BlechschereSchutzblechHintenD = 1322,
        BlechschereSchutzblechHintenH = 1332,
        LenkermontageK = 1411,
        LenkermontageD = 1421,
        LenkermontageH = 1431,
        SattelmontageComplK = 1511,
        SattelmontageComplD = 1521,
        SattelmontageComplH = 1531,
        PedalmontageK = 1512,
        PedalmontageD = 1522,
        PedalmontageH = 1532
    }
}
